# Application Server Port Details
# Cloud Stream Binding input destination details

server:
  port: 8086

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: cloud-stream-topic